### PR TITLE
add IPFS support

### PR DESCRIPTION
**Pull request by VrajGohil**
Related issue #1 

I've add IPFS upload functionality, please check. If user wants to share the file with ipfs, there is no need to login. Firebase functionality has been kept as it is. Also, JavaScript is not my first language so pardon any mistakes.😄

### CODE REVIEW

**Comment by Goku-kun** [comment]
Nice work getting it done. I checked out this commit and I think I'm having trouble accessing the file through IPFS generated link. The link just hangs until it times out. I'll have a look and figure out what's going on here and also fix the login page to give two options instead of directly showing the IPFS part right there. I'm not merging this pull request because there's still work needed to be done.

**Comment by VrajGohil** [comment]
Sure, it's just for reference

**Comment by Goku-kun** [comment]
Nice, man. What made you think about this brilliant idea? What's the reason that made you go to distributed web in the first place? Tell me more about it! @VrajGohil

**Comment by VrajGohil** [comment]
> Nice, man. What made you think about this brilliant idea? What's the reason that made you go to distributed web in the first place? Tell me more about it! @VrajGohil 

Actually I used to do everything with firebase, but that completely makes us dependent upon Google. Recently I had an experience that Google suspended my Admob account for production level app for no reason. I'm constantly looking for the open-source alternatives so we do not have to depend upon thier rules and policies.

For file sharing in particular, I had this idea for a while but didn't get time to execute it. I saw your project and found many things match with what I had in mind. For small files storage buckets are just fine, but what if I want to share large files like video. You know how large video files are these days, is it really feasible to store them (Except you got free GCP credits 😂). I know ipfs is not widely accepted, but I think this is the future.

**Comment by Goku-kun** [comment]
Oh, that makes total sense. I'll get on fixing the IPFS right away. It's a good viable alternative choice. Thanks for helping out. I'd also appreciate if you have any other suggestions/features on your mind and you would open issues for them in the repo. 

:)

**Review by Goku-kun — COMMENTED** [review]
I'm reviewing the code to find out what's going on with the generated link. Plus, I'll have to refactor to use the input component for both mode and I'll probably have to pull the state up for that as well. Anyways, I'll take it from here.

**Review by Goku-kun — COMMENTED** [review]
This is good work for someone whose first language ain't JavaScript. Thanks for all this hard work @VrajGohil.

**Comment by VrajGohil** [comment]
Thanks alot, I'll surely suggest if something comes up.

**Pull request closed without merging**
